### ISSUE TITLE
Giant images

### ISSUE THREAD

**Issue by gadenbuie** [malcolmbarrett/user_2021_canyon_of_success#1]
This repo showed up on my GitHub timeline and I was intrigued so I opened the presentation and started to worry when the slides took 10+ seconds to load. (They look great when they do load, btw!)

A little bit of poking around shows some vvvv huge images for the web:

```
> dir_ls("img") %>% file_info() %>% select(path, size) %>% arrange(desc(size))
# A tibble: 6 x 2
  path                              size
  <fs::path>                 <fs::bytes>
1 img/universe.jpg                40.82M
2 img/scaleable-earth.jpg         37.08M
3 img/consistent-diagram.jpg      32.08M
4 img/telephone.jpg                3.09M
5 img/canyon.jpg                   2.72M
6 img/pit.jpg                      1.19M
```

**Comment by malcolmbarrett** [comment]
My friend, you are the only person I know on planet earth who would post this 🤣 😘 

I actually don't much care about load time for talks (and especially on this one, which is done and recorded, as well as just being a lightning talk). Still, I am aware that this one is particularly beefy.

I'm not going to change this one (because I don't care 😇) but, for future reference, any tools you like for easily downscaling images without losing much quality?

**Comment by gadenbuie** [comment]
> I'm not going to change this one (because I don't care 😇) but, for future reference, any tools you like for easily downscaling images without losing much quality?

This one hurts right in the _too much gene_. #2

**Comment by gadenbuie** [comment]
> I actually don't much care about load time for talks

It's not so much load time but data usage. In _many_ parts of the world it could take more than 2 minutes to load all the images, and people may pay for the data they use (where this again is a lot of data). I wouldn't argue with you about not caring but I would suggest that you link to the repo rather than the rendered slides.

**Comment by malcolmbarrett** [comment]
get out of here garrick

**Comment by gadenbuie** [comment]
![okay I'm leaving now](https://media.giphy.com/media/8Bl0Gmc95WCsCOjS6V/giphy.gif)

**Comment by malcolmbarrett** [comment]
https://youtu.be/ZyMsVJmSL4w?t=5
